/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.Address = factory(root.KhIdentityVerification.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Address model module.
   * @module model/Address
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>Address</code>.
   * @alias module:model/Address
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Address} obj Optional instance to populate.
   * @return {module:model/Address} The populated <code>Address</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('UnitNumber')) {
        obj['UnitNumber'] = ApiClient.convertToType(data['UnitNumber'], 'String');
      }
      if (data.hasOwnProperty('BuildingNumber')) {
        obj['BuildingNumber'] = ApiClient.convertToType(data['BuildingNumber'], 'String');
      }
      if (data.hasOwnProperty('BuildingName')) {
        obj['BuildingName'] = ApiClient.convertToType(data['BuildingName'], 'String');
      }
      if (data.hasOwnProperty('StreetName')) {
        obj['StreetName'] = ApiClient.convertToType(data['StreetName'], 'String');
      }
      if (data.hasOwnProperty('StreetType')) {
        obj['StreetType'] = ApiClient.convertToType(data['StreetType'], 'String');
      }
      if (data.hasOwnProperty('City')) {
        obj['City'] = ApiClient.convertToType(data['City'], 'String');
      }
      if (data.hasOwnProperty('Suburb')) {
        obj['Suburb'] = ApiClient.convertToType(data['Suburb'], 'String');
      }
      if (data.hasOwnProperty('StateProvinceCode')) {
        obj['StateProvinceCode'] = ApiClient.convertToType(data['StateProvinceCode'], 'String');
      }
      if (data.hasOwnProperty('PostalCode')) {
        obj['PostalCode'] = ApiClient.convertToType(data['PostalCode'], 'String');
      }
      if (data.hasOwnProperty('Address1')) {
        obj['Address1'] = ApiClient.convertToType(data['Address1'], 'String');
      }
      if (data.hasOwnProperty('AddressType')) {
        obj['AddressType'] = ApiClient.convertToType(data['AddressType'], 'String');
      }
      if (data.hasOwnProperty('StateProvince')) {
        obj['StateProvince'] = ApiClient.convertToType(data['StateProvince'], 'String');
      }
    }
    return obj;
  }

  /**
   * Flat/Unit/Apartment number of address
   * @member {String} UnitNumber
   */
  exports.prototype['UnitNumber'] = undefined;
  /**
   * House / Civic / Building number of address
   * @member {String} BuildingNumber
   */
  exports.prototype['BuildingNumber'] = undefined;
  /**
   * Name of building
   * @member {String} BuildingName
   */
  exports.prototype['BuildingName'] = undefined;
  /**
   * Street name
   * @member {String} StreetName
   */
  exports.prototype['StreetName'] = undefined;
  /**
   * Street type of address (Typically St, Rd etc)
   * @member {String} StreetType
   */
  exports.prototype['StreetType'] = undefined;
  /**
   * City
   * @member {String} City
   */
  exports.prototype['City'] = undefined;
  /**
   * Suburb / Subdivision / Municipality
   * @member {String} Suburb
   */
  exports.prototype['Suburb'] = undefined;
  /**
   * State or province of address. US sources expect 2 characters. Australian sources expect 2 or 3 characters.
   * @member {String} StateProvinceCode
   */
  exports.prototype['StateProvinceCode'] = undefined;
  /**
   * ZIP Code or Postal Code
   * @member {String} PostalCode
   */
  exports.prototype['PostalCode'] = undefined;
  /**
   * It can be used to pass a compiled address field instead of sending individual address attributes (such as UnitNumber, BuidlingNumber, BuildingName, StreetName and StreetType)
   * @member {String} Address1
   */
  exports.prototype['Address1'] = undefined;
  /**
   * Type of address
   * @member {String} AddressType
   */
  exports.prototype['AddressType'] = undefined;
  /**
   * State or province of address
   * @member {String} StateProvince
   */
  exports.prototype['StateProvince'] = undefined;



  return exports;
}));


