/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.Communication = factory(root.KhIdentityVerification.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Communication model module.
   * @module model/Communication
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>Communication</code>.
   * @alias module:model/Communication
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Communication</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Communication} obj Optional instance to populate.
   * @return {module:model/Communication} The populated <code>Communication</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('MobileNumber')) {
        obj['MobileNumber'] = ApiClient.convertToType(data['MobileNumber'], 'String');
      }
      if (data.hasOwnProperty('Telephone')) {
        obj['Telephone'] = ApiClient.convertToType(data['Telephone'], 'String');
      }
      if (data.hasOwnProperty('Telephone2')) {
        obj['Telephone2'] = ApiClient.convertToType(data['Telephone2'], 'String');
      }
      if (data.hasOwnProperty('EmailAddress')) {
        obj['EmailAddress'] = ApiClient.convertToType(data['EmailAddress'], 'String');
      }
    }
    return obj;
  }

  /**
   * Mobile phone number of the individual to be verified.
   * @member {String} MobileNumber
   */
  exports.prototype['MobileNumber'] = undefined;
  /**
   * Telephone number of the individual to be verified.
   * @member {String} Telephone
   */
  exports.prototype['Telephone'] = undefined;
  /**
   * Additional Phone/Mobile Number of the individual to be verified.
   * @member {String} Telephone2
   */
  exports.prototype['Telephone2'] = undefined;
  /**
   * Email address of the individual to be verified.
   * @member {String} EmailAddress
   */
  exports.prototype['EmailAddress'] = undefined;



  return exports;
}));


