/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Communication', 'model/DriverLicence', 'model/Location', 'model/NationalId', 'model/Passport', 'model/PersonInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Communication'), require('./DriverLicence'), require('./Location'), require('./NationalId'), require('./Passport'), require('./PersonInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.DataFieldsKYC = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.Communication, root.KhIdentityVerification.DriverLicence, root.KhIdentityVerification.Location, root.KhIdentityVerification.NationalId, root.KhIdentityVerification.Passport, root.KhIdentityVerification.PersonInfo);
  }
}(this, function(ApiClient, Communication, DriverLicence, Location, NationalId, Passport, PersonInfo) {
  'use strict';



  /**
   * The DataFieldsKYC model module.
   * @module model/DataFieldsKYC
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>DataFieldsKYC</code>.
   * The data field name-value pairs for the data elements on which the verification is to be performed
   * @alias module:model/DataFieldsKYC
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>DataFieldsKYC</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataFieldsKYC} obj Optional instance to populate.
   * @return {module:model/DataFieldsKYC} The populated <code>DataFieldsKYC</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('PersonInfo')) {
        obj['PersonInfo'] = PersonInfo.constructFromObject(data['PersonInfo']);
      }
      if (data.hasOwnProperty('Location')) {
        obj['Location'] = Location.constructFromObject(data['Location']);
      }
      if (data.hasOwnProperty('Communication')) {
        obj['Communication'] = Communication.constructFromObject(data['Communication']);
      }
      if (data.hasOwnProperty('DriverLicence')) {
        obj['DriverLicence'] = DriverLicence.constructFromObject(data['DriverLicence']);
      }
      if (data.hasOwnProperty('NationalIds')) {
        obj['NationalIds'] = ApiClient.convertToType(data['NationalIds'], [NationalId]);
      }
      if (data.hasOwnProperty('Passport')) {
        obj['Passport'] = Passport.constructFromObject(data['Passport']);
      }
      if (data.hasOwnProperty('CountrySpecific')) {
        obj['CountrySpecific'] = ApiClient.convertToType(data['CountrySpecific'], {'String': {'String': 'String'}});
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PersonInfo} PersonInfo
   */
  exports.prototype['PersonInfo'] = undefined;
  /**
   * @member {module:model/Location} Location
   */
  exports.prototype['Location'] = undefined;
  /**
   * @member {module:model/Communication} Communication
   */
  exports.prototype['Communication'] = undefined;
  /**
   * @member {module:model/DriverLicence} DriverLicence
   */
  exports.prototype['DriverLicence'] = undefined;
  /**
   * National Identification Information. Supported Types: NationalID, Health, SocialService, TaxIDNumber.  See <a class=\"link-to-api\" href=\"https://developer.trulioo.com/docs/national-ids-supported-types\">Supported NationalIDs</a> to understand the Type to send with the ID number.
   * @member {Array.<module:model/NationalId>} NationalIds
   */
  exports.prototype['NationalIds'] = undefined;
  /**
   * @member {module:model/Passport} Passport
   */
  exports.prototype['Passport'] = undefined;
  /**
   * CountrySpecific fields  \"CountryCode\": {   \"Field1\" : \"Value\",   \"Field2\" : \"Value\"  }  Call <a class=\"link-to-api\" href=\"#getfields-2\">Get Fields</a> to get the list of fields that are valid for your configuration.
   * @member {Object.<String, Object.<String, String>>} CountrySpecific
   */
  exports.prototype['CountrySpecific'] = undefined;



  return exports;
}));


