/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AppendedField', 'model/DatasourceField', 'model/ServiceError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AppendedField'), require('./DatasourceField'), require('./ServiceError'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.DatasourceResult = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.AppendedField, root.KhIdentityVerification.DatasourceField, root.KhIdentityVerification.ServiceError);
  }
}(this, function(ApiClient, AppendedField, DatasourceField, ServiceError) {
  'use strict';



  /**
   * The DatasourceResult model module.
   * @module model/DatasourceResult
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>DatasourceResult</code>.
   * A result from a particular datasource
   * @alias module:model/DatasourceResult
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>DatasourceResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasourceResult} obj Optional instance to populate.
   * @return {module:model/DatasourceResult} The populated <code>DatasourceResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('DatasourceStatus')) {
        obj['DatasourceStatus'] = ApiClient.convertToType(data['DatasourceStatus'], 'String');
      }
      if (data.hasOwnProperty('DatasourceName')) {
        obj['DatasourceName'] = ApiClient.convertToType(data['DatasourceName'], 'String');
      }
      if (data.hasOwnProperty('DatasourceFields')) {
        obj['DatasourceFields'] = ApiClient.convertToType(data['DatasourceFields'], [DatasourceField]);
      }
      if (data.hasOwnProperty('AppendedFields')) {
        obj['AppendedFields'] = ApiClient.convertToType(data['AppendedFields'], [AppendedField]);
      }
      if (data.hasOwnProperty('Errors')) {
        obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
      }
      if (data.hasOwnProperty('FieldGroups')) {
        obj['FieldGroups'] = ApiClient.convertToType(data['FieldGroups'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} DatasourceStatus
   */
  exports.prototype['DatasourceStatus'] = undefined;
  /**
   * @member {String} DatasourceName
   */
  exports.prototype['DatasourceName'] = undefined;
  /**
   * @member {Array.<module:model/DatasourceField>} DatasourceFields
   */
  exports.prototype['DatasourceFields'] = undefined;
  /**
   * @member {Array.<module:model/AppendedField>} AppendedFields
   */
  exports.prototype['AppendedFields'] = undefined;
  /**
   * @member {Array.<module:model/ServiceError>} Errors
   */
  exports.prototype['Errors'] = undefined;
  /**
   * @member {Array.<String>} FieldGroups
   */
  exports.prototype['FieldGroups'] = undefined;



  return exports;
}));


