/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NormalizedDatasourceField'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NormalizedDatasourceField'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.NormalizedDatasourceGroupCountry = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.NormalizedDatasourceField);
  }
}(this, function(ApiClient, NormalizedDatasourceField) {
  'use strict';



  /**
   * The NormalizedDatasourceGroupCountry model module.
   * @module model/NormalizedDatasourceGroupCountry
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>NormalizedDatasourceGroupCountry</code>.
   * Datasource group config for country
   * @alias module:model/NormalizedDatasourceGroupCountry
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>NormalizedDatasourceGroupCountry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NormalizedDatasourceGroupCountry} obj Optional instance to populate.
   * @return {module:model/NormalizedDatasourceGroupCountry} The populated <code>NormalizedDatasourceGroupCountry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('RequiredFields')) {
        obj['RequiredFields'] = ApiClient.convertToType(data['RequiredFields'], [NormalizedDatasourceField]);
      }
      if (data.hasOwnProperty('OptionalFields')) {
        obj['OptionalFields'] = ApiClient.convertToType(data['OptionalFields'], [NormalizedDatasourceField]);
      }
      if (data.hasOwnProperty('AppendedFields')) {
        obj['AppendedFields'] = ApiClient.convertToType(data['AppendedFields'], [NormalizedDatasourceField]);
      }
      if (data.hasOwnProperty('OutputFields')) {
        obj['OutputFields'] = ApiClient.convertToType(data['OutputFields'], [NormalizedDatasourceField]);
      }
      if (data.hasOwnProperty('SourceType')) {
        obj['SourceType'] = ApiClient.convertToType(data['SourceType'], 'String');
      }
      if (data.hasOwnProperty('UpdateFrequency')) {
        obj['UpdateFrequency'] = ApiClient.convertToType(data['UpdateFrequency'], 'String');
      }
      if (data.hasOwnProperty('Coverage')) {
        obj['Coverage'] = ApiClient.convertToType(data['Coverage'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Description
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * Required Fields
   * @member {Array.<module:model/NormalizedDatasourceField>} RequiredFields
   */
  exports.prototype['RequiredFields'] = undefined;
  /**
   * Optional Fields
   * @member {Array.<module:model/NormalizedDatasourceField>} OptionalFields
   */
  exports.prototype['OptionalFields'] = undefined;
  /**
   * Appended Fields
   * @member {Array.<module:model/NormalizedDatasourceField>} AppendedFields
   */
  exports.prototype['AppendedFields'] = undefined;
  /**
   * Output Fields
   * @member {Array.<module:model/NormalizedDatasourceField>} OutputFields
   */
  exports.prototype['OutputFields'] = undefined;
  /**
   * Source Type
   * @member {String} SourceType
   */
  exports.prototype['SourceType'] = undefined;
  /**
   * Update Frequency
   * @member {String} UpdateFrequency
   */
  exports.prototype['UpdateFrequency'] = undefined;
  /**
   * Coverage
   * @member {String} Coverage
   */
  exports.prototype['Coverage'] = undefined;



  return exports;
}));


