/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PersonInfoAdditionalFields'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PersonInfoAdditionalFields'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.PersonInfo = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.PersonInfoAdditionalFields);
  }
}(this, function(ApiClient, PersonInfoAdditionalFields) {
  'use strict';



  /**
   * The PersonInfo model module.
   * @module model/PersonInfo
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>PersonInfo</code>.
   * Personal Information
   * @alias module:model/PersonInfo
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>PersonInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersonInfo} obj Optional instance to populate.
   * @return {module:model/PersonInfo} The populated <code>PersonInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('FirstGivenName')) {
        obj['FirstGivenName'] = ApiClient.convertToType(data['FirstGivenName'], 'String');
      }
      if (data.hasOwnProperty('MiddleName')) {
        obj['MiddleName'] = ApiClient.convertToType(data['MiddleName'], 'String');
      }
      if (data.hasOwnProperty('FirstSurName')) {
        obj['FirstSurName'] = ApiClient.convertToType(data['FirstSurName'], 'String');
      }
      if (data.hasOwnProperty('SecondSurname')) {
        obj['SecondSurname'] = ApiClient.convertToType(data['SecondSurname'], 'String');
      }
      if (data.hasOwnProperty('ISOLatin1Name')) {
        obj['ISOLatin1Name'] = ApiClient.convertToType(data['ISOLatin1Name'], 'String');
      }
      if (data.hasOwnProperty('DayOfBirth')) {
        obj['DayOfBirth'] = ApiClient.convertToType(data['DayOfBirth'], 'Number');
      }
      if (data.hasOwnProperty('MonthOfBirth')) {
        obj['MonthOfBirth'] = ApiClient.convertToType(data['MonthOfBirth'], 'Number');
      }
      if (data.hasOwnProperty('YearOfBirth')) {
        obj['YearOfBirth'] = ApiClient.convertToType(data['YearOfBirth'], 'Number');
      }
      if (data.hasOwnProperty('MinimumAge')) {
        obj['MinimumAge'] = ApiClient.convertToType(data['MinimumAge'], 'Number');
      }
      if (data.hasOwnProperty('Gender')) {
        obj['Gender'] = ApiClient.convertToType(data['Gender'], 'String');
      }
      if (data.hasOwnProperty('AdditionalFields')) {
        obj['AdditionalFields'] = PersonInfoAdditionalFields.constructFromObject(data['AdditionalFields']);
      }
    }
    return obj;
  }

  /**
   * First name of the individual to be verified. Dual purpose First Name or Initial.
   * @member {String} FirstGivenName
   */
  exports.prototype['FirstGivenName'] = undefined;
  /**
   * Second given name of the individual to be verified. Dual purpose Middle Name or Initial.
   * @member {String} MiddleName
   */
  exports.prototype['MiddleName'] = undefined;
  /**
   * First (paternal) family name of the individual to be verified.
   * @member {String} FirstSurName
   */
  exports.prototype['FirstSurName'] = undefined;
  /**
   * Second family name of the individual to be verified.
   * @member {String} SecondSurname
   */
  exports.prototype['SecondSurname'] = undefined;
  /**
   * Enter full name in ISO Latin-1 character set. Used for data sources that require the person’s name in ISO Latin-1 format (i.e. as Passport MRZ).
   * @member {String} ISOLatin1Name
   */
  exports.prototype['ISOLatin1Name'] = undefined;
  /**
   * Day of birth date (i.e. 23 for a date of birth of 23/11/1975).
   * @member {Number} DayOfBirth
   */
  exports.prototype['DayOfBirth'] = undefined;
  /**
   * Month of birth date (i.e. 11 for a date of birth of 23/11/1975).
   * @member {Number} MonthOfBirth
   */
  exports.prototype['MonthOfBirth'] = undefined;
  /**
   * Year of birth date (i.e. 1975 for a date of birth of 23/11/1975).
   * @member {Number} YearOfBirth
   */
  exports.prototype['YearOfBirth'] = undefined;
  /**
   * Minimum permitted age of the individual. GlobalGateway calculates age of individual and compares it to this number.
   * @member {Number} MinimumAge
   */
  exports.prototype['MinimumAge'] = undefined;
  /**
   * Single character M / F (M = Male, F = Female).
   * @member {String} Gender
   */
  exports.prototype['Gender'] = undefined;
  /**
   * @member {module:model/PersonInfoAdditionalFields} AdditionalFields
   */
  exports.prototype['AdditionalFields'] = undefined;



  return exports;
}));


