/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DatasourceResult', 'model/RecordRule', 'model/ServiceError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DatasourceResult'), require('./RecordRule'), require('./ServiceError'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.Record = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.DatasourceResult, root.KhIdentityVerification.RecordRule, root.KhIdentityVerification.ServiceError);
  }
}(this, function(ApiClient, DatasourceResult, RecordRule, ServiceError) {
  'use strict';



  /**
   * The Record model module.
   * @module model/Record
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>Record</code>.
   * @alias module:model/Record
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Record</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Record} obj Optional instance to populate.
   * @return {module:model/Record} The populated <code>Record</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('TransactionRecordID')) {
        obj['TransactionRecordID'] = ApiClient.convertToType(data['TransactionRecordID'], 'String');
      }
      if (data.hasOwnProperty('RecordStatus')) {
        obj['RecordStatus'] = ApiClient.convertToType(data['RecordStatus'], 'String');
      }
      if (data.hasOwnProperty('DatasourceResults')) {
        obj['DatasourceResults'] = ApiClient.convertToType(data['DatasourceResults'], [DatasourceResult]);
      }
      if (data.hasOwnProperty('Errors')) {
        obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
      }
      if (data.hasOwnProperty('Rule')) {
        obj['Rule'] = RecordRule.constructFromObject(data['Rule']);
      }
    }
    return obj;
  }

  /**
   * The TransactionRecordID, this is the ID you will use to fetch the transaction again.
   * @member {String} TransactionRecordID
   */
  exports.prototype['TransactionRecordID'] = undefined;
  /**
   * 'match' or 'nomatch' if the verification passed the rules configured on your account this will be 'match'.
   * @member {String} RecordStatus
   */
  exports.prototype['RecordStatus'] = undefined;
  /**
   * Results for each datasource that was queried.
   * @member {Array.<module:model/DatasourceResult>} DatasourceResults
   */
  exports.prototype['DatasourceResults'] = undefined;
  /**
   * @member {Array.<module:model/ServiceError>} Errors
   */
  exports.prototype['Errors'] = undefined;
  /**
   * @member {module:model/RecordRule} Rule
   */
  exports.prototype['Rule'] = undefined;



  return exports;
}));


