/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DataField', 'model/Record', 'model/ServiceError', 'model/TransactionRecordResultAllOf', 'model/VerifyResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DataField'), require('./Record'), require('./ServiceError'), require('./TransactionRecordResultAllOf'), require('./VerifyResult'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.TransactionRecordResult = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.DataField, root.KhIdentityVerification.Record, root.KhIdentityVerification.ServiceError, root.KhIdentityVerification.TransactionRecordResultAllOf, root.KhIdentityVerification.VerifyResult);
  }
}(this, function(ApiClient, DataField, Record, ServiceError, TransactionRecordResultAllOf, VerifyResult) {
  'use strict';



  /**
   * The TransactionRecordResult model module.
   * @module model/TransactionRecordResult
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>TransactionRecordResult</code>.
   * @alias module:model/TransactionRecordResult
   * @class
   * @implements module:model/VerifyResult
   * @implements module:model/TransactionRecordResultAllOf
   */
  var exports = function() {
    var _this = this;

    VerifyResult.call(_this);
    TransactionRecordResultAllOf.call(_this);
  };

  /**
   * Constructs a <code>TransactionRecordResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionRecordResult} obj Optional instance to populate.
   * @return {module:model/TransactionRecordResult} The populated <code>TransactionRecordResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      VerifyResult.constructFromObject(data, obj);
      TransactionRecordResultAllOf.constructFromObject(data, obj);
      if (data.hasOwnProperty('TransactionID')) {
        obj['TransactionID'] = ApiClient.convertToType(data['TransactionID'], 'String');
      }
      if (data.hasOwnProperty('UploadedDt')) {
        obj['UploadedDt'] = ApiClient.convertToType(data['UploadedDt'], 'Date');
      }
      if (data.hasOwnProperty('CountryCode')) {
        obj['CountryCode'] = ApiClient.convertToType(data['CountryCode'], 'String');
      }
      if (data.hasOwnProperty('ProductName')) {
        obj['ProductName'] = ApiClient.convertToType(data['ProductName'], 'String');
      }
      if (data.hasOwnProperty('Record')) {
        obj['Record'] = Record.constructFromObject(data['Record']);
      }
      if (data.hasOwnProperty('CustomerReferenceID')) {
        obj['CustomerReferenceID'] = ApiClient.convertToType(data['CustomerReferenceID'], 'String');
      }
      if (data.hasOwnProperty('Errors')) {
        obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
      }
      if (data.hasOwnProperty('InputFields')) {
        obj['InputFields'] = ApiClient.convertToType(data['InputFields'], [DataField]);
      }
    }
    return obj;
  }

  /**
   * The id for the transaction it will be a GUID.
   * @member {String} TransactionID
   */
  exports.prototype['TransactionID'] = undefined;
  /**
   * Time in UTC.
   * @member {Date} UploadedDt
   */
  exports.prototype['UploadedDt'] = undefined;
  /**
   * Country Code
   * @member {String} CountryCode
   */
  exports.prototype['CountryCode'] = undefined;
  /**
   * Product Name
   * @member {String} ProductName
   */
  exports.prototype['ProductName'] = undefined;
  /**
   * @member {module:model/Record} Record
   */
  exports.prototype['Record'] = undefined;
  /**
   * Customer Reference ID
   * @member {String} CustomerReferenceID
   */
  exports.prototype['CustomerReferenceID'] = undefined;
  /**
   * See <a class=\"link-to-api\" href=\"#section-service-errors\">Errors</a> for explanation of any error encountered.
   * @member {Array.<module:model/ServiceError>} Errors
   */
  exports.prototype['Errors'] = undefined;
  /**
   * @member {Array.<module:model/DataField>} InputFields
   */
  exports.prototype['InputFields'] = undefined;

  // Implement VerifyResult interface:
  /**
   * The id for the transaction it will be a GUID.
   * @member {String} TransactionID
   */
exports.prototype['TransactionID'] = undefined;

  /**
   * Time in UTC.
   * @member {Date} UploadedDt
   */
exports.prototype['UploadedDt'] = undefined;

  /**
   * Country Code
   * @member {String} CountryCode
   */
exports.prototype['CountryCode'] = undefined;

  /**
   * Product Name
   * @member {String} ProductName
   */
exports.prototype['ProductName'] = undefined;

  /**
   * @member {module:model/Record} Record
   */
exports.prototype['Record'] = undefined;

  /**
   * Customer Reference ID
   * @member {String} CustomerReferenceID
   */
exports.prototype['CustomerReferenceID'] = undefined;

  /**
   * See <a class=\"link-to-api\" href=\"#section-service-errors\">Errors</a> for explanation of any error encountered.
   * @member {Array.<module:model/ServiceError>} Errors
   */
exports.prototype['Errors'] = undefined;

  // Implement TransactionRecordResultAllOf interface:
  /**
   * @member {Array.<module:model/DataField>} InputFields
   */
exports.prototype['InputFields'] = undefined;



  return exports;
}));


