/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DataField'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DataField'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.TransactionRecordResultAllOf = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.DataField);
  }
}(this, function(ApiClient, DataField) {
  'use strict';



  /**
   * The TransactionRecordResultAllOf model module.
   * @module model/TransactionRecordResultAllOf
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new <code>TransactionRecordResultAllOf</code>.
   * @alias module:model/TransactionRecordResultAllOf
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>TransactionRecordResultAllOf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionRecordResultAllOf} obj Optional instance to populate.
   * @return {module:model/TransactionRecordResultAllOf} The populated <code>TransactionRecordResultAllOf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('InputFields')) {
        obj['InputFields'] = ApiClient.convertToType(data['InputFields'], [DataField]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/DataField>} InputFields
   */
  exports.prototype['InputFields'] = undefined;



  return exports;
}));


