/**
 * kh_identity_verification
 * To run tests transactions on our trial endpoint in postman: [![Run in Postman](https://run.pstmn.io/button.svg)](https://www.getpostman.com/run-collection/a58f438d101278e2bc62) 
 *
 * The version of the OpenAPI document: 1.0.0-alpha.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TransactionRecordResult', 'model/VerifyRequest', 'model/VerifyResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TransactionRecordResult'), require('../model/VerifyRequest'), require('../model/VerifyResult'));
  } else {
    // Browser globals (root is window)
    if (!root.KhIdentityVerification) {
      root.KhIdentityVerification = {};
    }
    root.KhIdentityVerification.VerificationsApi = factory(root.KhIdentityVerification.ApiClient, root.KhIdentityVerification.TransactionRecordResult, root.KhIdentityVerification.VerifyRequest, root.KhIdentityVerification.VerifyResult);
  }
}(this, function(ApiClient, TransactionRecordResult, VerifyRequest, VerifyResult) {
  'use strict';

  /**
   * Verifications service.
   * @module api/VerificationsApi
   * @version 1.0.0-alpha.2
   */

  /**
   * Constructs a new VerificationsApi. 
   * @alias module:api/VerificationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getTransactionRecord operation.
     * @callback module:api/VerificationsApi~getTransactionRecordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TransactionRecordResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Transaction Record
     * This method is used to retrieve the request and results of a verification performed using the verify method.   The response for this method includes the same information as verify method's response, along with data present in the input fields of the verify request.
     * @param {String} id The TransactionRecordID from the Verify response, this will be a GUID
     * @param {module:api/VerificationsApi~getTransactionRecordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TransactionRecordResult}
     */
    this.getTransactionRecord = function(id, callback) {
      var postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTransactionRecord");
      }

      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json'];
      var returnType = TransactionRecordResult;
      return this.apiClient.callApi(
        '/verifications/v1/transactionrecord/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the verify operation.
     * @callback module:api/VerificationsApi~verifyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VerifyResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Verify
     * Calling this method will perform a verification. If your account includes address cleansing set the CleansedAddress flag to get  additional address information in the result.  You can query configuration to get what fields are available to you in each country.  It is also possible to get sample requests from the customer portal. If you are configured for a sandbox account make sure to call Get Test Entities to get test data for a country you want to try. Sandbox accounts only use these test entities and so trying to verify with any other data will result in no matches being found.
     * @param {module:model/VerifyRequest} verifyRequest 
     * @param {module:api/VerificationsApi~verifyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VerifyResult}
     */
    this.verify = function(verifyRequest, callback) {
      var postBody = verifyRequest;
      // verify the required parameter 'verifyRequest' is set
      if (verifyRequest === undefined || verifyRequest === null) {
        throw new Error("Missing the required parameter 'verifyRequest' when calling verify");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json', 'text/json'];
      var accepts = ['application/json', 'text/json'];
      var returnType = VerifyResult;
      return this.apiClient.callApi(
        '/verifications/v1/verify', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
