# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Install, Build
        run: |
          sudo npm install -g babel-cli          
          cd javascript
          npm install
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: npm whoami
      - name: Run CI
        run: |
          cd javascript
          npm ci
      - name: Run Semantic Release
        run: |
          cd javascript
          npm install --save-dev semantic-release
          # npm run semantic-release
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
